language: cpp
comiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:libreoffice/ppa
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq g++-4.7 openmpi-bin openmpi-common openmpi-dev cmake
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
 - sudo update-alternatives --set gcc /usr/bin/gcc-4.7

script:
 - mkdir build && cd build && cmake ../
 - make
 - make test
