sudo: required
dist: trusty

language: cpp
comiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev cmake

script:
 - mkdir build && cd build && cmake ../
 - make
 - make test
