# SPDX-FileCopyrightText: 2024 Technical University of Munich
#
# SPDX-License-Identifier: BSD-3-Clause

name: unittest
on:
  - push

jobs:
  unittest:
    name: unittest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: install-packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install -y libomp-dev libopenmpi-dev openmpi-bin openmpi-common ninja-build
          sudo apt-get install -y cxxtest

      - name: build-nompi
        run: |
          mkdir build-nompi
          cd build-nompi
          cmake .. -GNinja -DUSE_MPI=OFF -DTESTING=ON
          ninja
          ctest --rerun-failed --output-on-failure
          cd ..

      - name: build-mpi
        run: |
          mkdir build-mpi
          cd build-mpi
          cmake .. -GNinja -DUSE_MPI=ON -DTESTING=ON
          ninja
          ctest --rerun-failed --output-on-failure
          cd ..
